name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image
        run: |
          docker build . -t zombie19x/demo-node-app:latest
          docker push zombie19x/demo-node-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEMO_EC2_IP }}
          username: ${{ secrets.DEMO_EC2_USER }}
          key: ${{ secrets.DEMO_EC2_SSH_KEY }}
          script: |
            sudo docker pull zombie19x/demo-node-app:latest
            sudo docker compose -d -f /app/demo-node-app/docker-compose.yml up
